os: linux
dist: bionic
language: php
php:
  - '7.4'
  - '7.3'
  - '7.2'
services:
  - docker

install:
- curl https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz | tar -xz
- .github/setup-docker.sh

before_script:
# Ensure that DB2CLIINIPATH gets passed to the tests
- echo 'variables_order = "EGPCS"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

script:
- phpize
- ./configure --with-IBM_DB2=$PWD/clidriver
- make
- |
  cat <<EOF > db2cli.ini
  [SAMPLE]
  Hostname=localhost
  Protocol=TCPIP
  Port=60000
  Database=sample
  EOF
- cat db2cli.ini
- cat Makefile
- .github/run-tests.sh

after_failure:
- cat report.txt
