name: Test ibm_db

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  run:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-16.04]
        php-versions: ['5.6', '7.2', '7.3', '7.4']
    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}
    services: 
      db2:
        image: ibmcom/db2
        ports: 
        - 60000:50000
        env:
          LICENSE: accept
          DB2INST1_PASSWORD: password
          DBNAME: sample
          ARCHIVE_LOGS: false
          AUTOCONFIG: false
        volumes: 
        - /github/home/database:/database
        options: --name db2 --privileged=true

 
    steps:

      - name: Checkout code
        uses: actions/checkout@v1
      
      - name: Wait for completion
        run: ./.github/check-start.sh
      
      - name: Start Db2
        run: docker exec db2 bash -c "su - db2inst1"
        
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}   
          tools: phpize
          ini-values: variables_order="EGPCS"

      - name: Download CLI driver 
        run: curl https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz | tar -xz
      
      - run: phpize
      - run: ./configure --with-IBM_DB2=$PWD/clidriver
      - run: make
      - run: |
            cat <<EOF > db2cli.ini
            [SAMPLE]
            Hostname=localhost
            Protocol=TCPIP
            Port=60000
            Database=sample
            EOF
      - run: cat db2cli.ini
      - run: cat Makefile
      - run: .github/run-tests.sh
